---
title: "Exploratory Analysis"
output: html_notebook
---

Imports
```{r}
#Import Libraries
library(tidyverse)
library(readxl)
library(reticulate)
library(ggplot2)
library(ggpubr)

#Import Python
source("..\\config.R") #sources python_path
use_python(python_path, required = TRUE)

#Import Data
source_python('feature_creation.py')
```

Data Cleaning & Transformation
```{r}
modeling_data <- df_features %>%
  select(-SEVEN_LETTERS, -CENTER_LETTER) %>% #Drop non-numerical variables
  mutate(NUM_SOLUTIONS_LOG = log(NUM_SOLUTIONS, 10)) #Log transform target variable
```

Distribution of Data
```{r}
#KDE of Number of Solutions (Raw)
density_raw <- ggdensity(modeling_data, x = "NUM_SOLUTIONS", fill = "lightgray", title = "Number of Solutions (Raw)") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")

#KDE of Number of Solutions (Log Transformation)
density_log <- ggdensity(modeling_data, x = "NUM_SOLUTIONS_LOG", fill = "lightgray", title = "Number of Solutions (Log Transformation)") +
  stat_overlay_normal_density(color = "red", linetype = "dashed")

#Density Comparison
figure_density <- ggarrange(density_raw, density_log,
                    ncol = 2, nrow = 1) %>%
  annotate_figure(top = "Solutions KDE Before & After Transformation")

figure_density
```


Calculate Pearson Correlations
```{r}
#Correlation Matrix
cor_matrix <- cor(modeling_data, method = "pearson")

#Keep Correlations for number of solutions only
cor_summary <- cor_matrix %>%
  as.data.frame() %>%
  select(NUM_SOLUTIONS, NUM_SOLUTIONS_LOG) %>%
  rename(
    correlation_raw = NUM_SOLUTIONS,
    correlation_log = NUM_SOLUTIONS_LOG) %>%
  mutate(
    correlation_raw_mag = abs(correlation_raw),
    correlation_log_mag = abs(correlation_log))
```

Impact of Number of Vowels
```{r}
vowesl_scatter <- ggplot(data = modeling_data,
       aes(x = factor(NUM_VOWELS), y= NUM_SOLUTIONS)) +
  geom_boxplot()

```

